name: Release Build

on:
  push:
    branches:
      - main
    tags:
      - '**'

jobs:
  build:
    name: Build Docker Image
    uses: ./.github/workflows/docker-build.yaml
    with:
      tag: ${{ github.ref_name }}
      application_version: ${{ github.ref_name }}