name: Reusable Docker Build

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
        description: "Docker image tag"
      application_version:
        required: true
        type: string
        description: "Application version to build"

env:
  platforms: linux/amd64

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Login to the registry
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        uses: docker/build-push-action@v7
        with:
          context: .
          push: true
          platforms: ${{ env.platforms }}
          build-args: |
            APPLICATION_VERSION=${{ inputs.application_version }}
          tags: ghcr.io/${{ github.repository }}:${{ inputs.tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
